package mind.need;

import mind.goals.IGoal;

public class CreativityNeed extends AbstractNeed {

	/**
	 * potentially some system of such needs being generated by an inspiration
	 * 
	 * @param deg
	 */
	public CreativityNeed(Degree deg/* , Feeling inspiration */) {
		super(NeedType.CREATIVITY, deg);
	}

	@Override
	public IGoal genIndividualGoal() {
		return null;
	}

	@Override
	public IGoal genSocietalGoal() {
		return null;
	}

}
